name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/tug-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o bin/tug-darwin-amd64

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/tug-linux-amd64
            bin/tug-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
