name: Build and Release

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Print release tag
        run: echo "Release tag is ${{ github.event.release.tag_name }}"

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o "bin/dscli-linux-amd64-${{ github.event.release.tag_name }}"
          GOOS=darwin GOARCH=amd64 go build -o "bin/dscli-darwin-amd64-${{ github.event.release.tag_name }}"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/dscli-linux-amd64
            bin/dscli-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
